/**
 * Per-quotation verification register.
 *
 * Search Console shows this archive's only top-3 rankings all sit in the
 * "quote source" family: readers arrive holding a sentence, a name, or a
 * fragment, and they want the locator. The pages that rank for those queries
 * are the ones that answer attribution questions explicitly instead of only
 * presenting the passage.
 *
 * This register holds the material that answer needs and that no scraper site
 * has: the original-language wording where a single original exists, the
 * variants that circulate in place of it, and the specific thing readers get
 * wrong about who said it and in what sense.
 *
 * Deliberately a register, not a template. Nothing here is generated by
 * pattern: an entry exists only where there is something true and specific to
 * say. Pages without an entry render the citation block alone rather than
 * filler, because a boilerplate paragraph repeated across 690 pages is the
 * exact thin-content signature that triggered the August quality re-evaluation.
 *
 * Adding a batch: append entries, then add the IDs to VERIFICATION_BATCHES.
 */

export type VerificationNote = {
  /** The wording in the language the author wrote, when one original exists. */
  original?: {
    language: string;
    text: string;
    /** What the rendering into English added, dropped, or decided. */
    note?: string;
  };
  /** Wording that circulates in place of the cited text, and why it differs. */
  variants?: string[];
  /** Who gets credited wrongly, where the line really sits, and what it means. */
  attribution: string;
  /** Date this record was last checked against the cited edition. */
  lastVerified: string;
};

export const quoteVerification: Record<string, VerificationNote> = {
  Q0001: {
    original: {
      language: "Ancient Greek",
      text: "ὁ δὲ ἀνεξέταστος βίος οὐ βιωτὸς ἀνθρώπῳ.",
      note:
        "The Greek word order is “the unexamined life, not to be lived, for a human being.” Most English versions drop “for a human being,” which is where the claim is limited to a human life and not to life as such.",
    },
    variants: [
      "The unexamined life is not worth living.",
      "An unexamined life is not worth living.",
    ],
    attribution:
      "Socrates wrote nothing. This is Plato's rendering of Socrates' speech in the Apology, and the line falls in the penalty phase after the guilty verdict — Socrates is refusing a sentence of silence, not offering a maxim about self-help. Quoting it as a general exhortation to reflection drops the occasion it was spoken on.",
    lastVerified: "2026-09-14",
  },

  Q0002: {
    original: {
      language: "Ancient Greek",
      text: "ἃ μὴ οἶδα οὐδὲ οἴομαι εἰδέναι.",
      note:
        "Literally “what I do not know, I do not think I know either.” The archive's English rendering compresses this to a claim about claimed knowledge.",
    },
    variants: [
      "I know that I know nothing.",
      "I know one thing: that I know nothing.",
    ],
    attribution:
      "“I know that I know nothing” is a later compression, not a sentence in Plato. The Apology passage is narrower and more careful: Socrates claims only that where he lacks knowledge he also does not believe he has it. The popular version turns a claim about his own position into a paradox about knowledge in general.",
    lastVerified: "2026-09-14",
  },

  Q0003: {
    original: {
      language: "Ancient Greek",
      text: "βούλομαι μᾶλλον ἀδικεῖσθαι ἢ ἀδικεῖν.",
      note:
        "“I would rather be wronged than do wrong.” The English noun-form rendering (“it is worse to do injustice than to suffer it”) converts Socrates' stated preference into a ranked claim that the interlocutor Polus immediately contests.",
    },
    attribution:
      "Said by Socrates in the Gorgias, at 469b–c, and it is an argued conclusion rather than an aphorism: Polus finds it absurd and the rest of the dialogue is Socrates defending it. The line is often lifted out of that exchange and quoted as received wisdom, which loses that it was the controversial position.",
    lastVerified: "2026-09-14",
  },

  Q0004: {
    original: {
      language: "Ancient Greek",
      text: "οὐδεὶς ἑκὼν ἁμαρτάνει.",
      note:
        "“No one errs willingly.” Also stated near the end of the Gorgias (509e), which matters because the Protagoras passage is where the argument is built, not where it is first asserted.",
    },
    attribution:
      "One of the two claims usually labelled the Socratic paradoxes — the other being that virtue is knowledge. Read on its own it sounds like a denial of responsibility; in context it follows from the premise that everyone acts toward what they believe good, so acting badly is a failure of belief rather than of will.",
    lastVerified: "2026-09-14",
  },

  Q0032: {
    original: {
      language: "Latin",
      text: "Non est ad astra mollis e terris via.",
      note:
        "Word for word: “there is no soft road from the earth to the stars.” The adjective is mollis — soft, yielding, easy to tread — and most English versions render it “easy,” which keeps the sense but loses the tactile contrast with the hard road.",
    },
    variants: [
      "There is no easy way from the earth to the stars.",
      "To the stars through difficulties.",
      "Per aspera ad astra.",
    ],
    attribution:
      "The line is from Seneca's tragedy Hercules Furens, at verse 437 — a play, not the Letters to Lucilius where most circulating Seneca quotations originate, and the two are constantly confused. It is also routinely merged with “per aspera ad astra,” a separate Latin motto that is not in Seneca and whose wording is later. The play's line is spoken inside the drama and carries the dramatic situation with it; the film-poster version has shed all of that.",
    lastVerified: "2026-09-14",
  },

  Q0054: {
    original: {
      language: "Latin and French",
      text: "Ego cogito, ergo sum.",
      note:
        "The Latin appears in the Principles of Philosophy I, §7. The French original of the same thought is “Je pense, donc je suis,” in the Discourse on the Method IV. The three-word tag “cogito ergo sum” is a compression of the Latin, not a quotation in either text.",
    },
    variants: ["Cogito ergo sum.", "I think, therefore I am (I exist)."],
    attribution:
      "In the Meditations Descartes does not use the famous formula at all; he writes “Ego sum, ego existo” (I am, I exist) at the second Meditation. Passing the “cogito” off as the Meditations wording confuses the work where the argument is made with the works where Descartes summarised it.",
    lastVerified: "2026-09-14",
  },

  Q0055: {
    original: {
      language: "Latin",
      text:
        "Semel in vita de omnibus, quantum fieri potest, esse dubitandum.",
      note:
        "“Once in a life, as far as possible, everything must be doubted.” The words “once in a lifetime” carry the whole method: this is a single act of demolition, not a standing policy.",
    },
    attribution:
      "The sentence is Descartes' statement of the method of the first Meditation. It is routinely recited as a general endorsement of scepticism, which inverts it: Descartes doubts once in order to find something that cannot be doubted, and the point of the exercise is the foundation he reaches at the end of the second Meditation.",
    lastVerified: "2026-09-14",
  },

  Q0059: {
    original: {
      language: "French",
      text: "Le cœur a ses raisons que la raison ne connaît point.",
      note:
        "The archive cites the Brunschvicg numbering. The Pensées are numbered differently in the Lafuma and Sellier editions, so the section number will not match a source that uses a different scheme — a real hazard for anyone trying to check the line.",
    },
    attribution:
      "The French is usually mistranslated as “the heart has reasons that reason cannot know,” which makes it a rejection of reason. The French says reason does not know them, not that they are unknowable — the heart's reasons are ones the discursive intellect has not reached. Pascal's target is the theology of his own century, not reason as such.",
    lastVerified: "2026-09-14",
  },

  Q0062: {
    original: {
      language: "French",
      text: "L'homme est né libre, et partout il est dans les fers.",
      note:
        "The French noun is the same word for chains and for fetters; “in chains” loses that the image is specifically of slave irons.",
    },
    attribution:
      "This is the opening sentence of On the Social Contract I.1. Because it works as a standalone lament it is read as Rousseau announcing a fixed condition, whereas the sentence opens a book whose point is that the chains were made and can be unmade — the “problem” he names in I.1 is to find a legitimate form of association, not to mourn an unavoidable loss of freedom.",
    lastVerified: "2026-09-14",
  },

  Q0070: {
    original: {
      language: "German",
      text: "Aus der Kriegsschule des Lebens. — Was mich nicht umbringt, macht mich stärker.",
      note:
        "The German has two parts. The first, “From the military school of life,” is a heading Nietzsche gives the aphorism; the second is the sentence everyone quotes.",
    },
    variants: [
      "What does not kill me makes me stronger.",
      "That which does not kill us makes us stronger.",
    ],
    attribution:
      "The plural “us” is the most common alteration of the German, which is first-person singular (“mich”). It sits in Twilight of the Idols among the thirty-eight “Maxims and Arrows,” which is to say in a work of compressed polemic rather than a statement of doctrine, and Nietzsche does not gloss it anywhere.",
    lastVerified: "2026-09-14",
  },

  Q0071: {
    original: {
      language: "Latin",
      text: "Amor fati.",
      note:
        "Latin, coined as a phrase rather than quoted from an earlier author. The German sentence it sits in is “Amor fati: das sei von nun an meine Liebe!”",
    },
    attribution:
      "“Amor fati” is Nietzsche's own formulation in The Gay Science §276 — it is not a Stoic term of art, however frequently it is filed under Stoicism. Epictetus and Marcus Aurelius counsel acceptance of what is not in our control; Nietzsche's love of fate also wills that the past have been exactly as it was, which is a heavier demand and connects to the eternal recurrence shortly after.",
    lastVerified: "2026-09-14",
  },

  Q0072: {
    original: {
      language: "German",
      text: "Wie man wird, was man ist.",
      note:
        "The subtitle of Ecce Homo. The thought is older than the book — Nietzsche credits Pindar, whose second Pythian ode has “become such as you are, having learned what that is.”",
    },
    variants: ["Become what you are.", "How one becomes what one is."],
    attribution:
      "“Become what you are” usually reaches readers through Pindar or through the English title of the Ecce Homo subtitle, and it is then read as an encouragement to self-expression. In Nietzsche the phrase is about the long, unfree process by which a person's disparate drives are disciplined into a single style — the becoming is not willed, it is survived.",
    lastVerified: "2026-09-14",
  },

  Q0074: {
    original: {
      language: "German",
      text:
        "Dieses Leben, wie du es jetzt lebst und gelebt hast, wirst du noch einmal und noch unzählige Male leben müssen.",
      note:
        "The demon's speech in The Gay Science §341. The English rendering preserves the sentence break, which is what makes the passage overwhelming.",
    },
    variants: [
      "What if a demon told you this life would repeat endlessly?",
      "Eternal recurrence.",
    ],
    attribution:
      "This is the thought experiment of the eternal recurrence — and in §341 it is a demon's speech whose purpose is a test, closing with the question of whether you could want it. Readers often present the recurrence as Nietzsche's cosmology, a claim about how the universe actually runs; in The Gay Science it is a condition posed to a single reader, and the later notes in which he took it more literally are a different and much cruder form of the idea.",
    lastVerified: "2026-09-14",
  },

  Q0102: {
    original: {
      language: "Ancient Greek",
      text: "τὸ τῇ μέλισσῃ μὴ συμφέρον οὐδὲ τῷ συμμέλει συμφέρει.",
      note:
        "The Greek second noun is συμμέλει, the swarm. The standard English rendering says “hive,” which names the structure rather than the colony.",
    },
    variants: [
      "What is not good for the hive is not good for the bee.",
      "What is not beneficial to the swarm is not beneficial to the bee.",
      "What is not good for the swarm is not good for the bee.",
    ],
    attribution:
      "Meditations VI.54, where the sentence belongs to Marcus Aurelius' argument that he was made for the whole and cannot act against it. The image is a swarm — a body that the individual bee physically cannot survive leaving — and the popular English substitution of “hive” bends it toward a claim about institutions and conformity, which is the opposite of the Stoic point about natural membership.",
    lastVerified: "2026-09-14",
  },

  Q0120: {
    original: {
      language: "English",
      text: "Truth happens to an idea. It becomes true, is made true by events.",
      note:
        "Two sentences, from Lecture VI, “Pragmatism's Conception of Truth,” in Pragmatism (1907). The second sentence is what the first means.",
    },
    variants: [
      "Truth happens to an idea.",
      "Truth is what happens to an idea.",
    ],
    attribution:
      "Quoted at the first sentence alone it reads as relativism — as if anything could become true. James' argument is the opposite: an idea is made true by its verification in events, so the second sentence is not an elaboration but the claim itself. Cutting it off is the single most common way this passage is misrepresented, and readers who arrive looking for the source are usually looking because the one-sentence version seemed to say something James would have denied.",
    lastVerified: "2026-09-14",
  },

  Q0134: {
    original: {
      language: "Classical Chinese",
      text:
        "學而時習之，不亦說乎？有朋自遠方來，不亦樂乎？人不知而不慍，不亦君子乎？",
      note:
        "Three rhetorical questions opening the Analects. The archive's rendering expands each into English clause order; the Chinese is far more compact.",
    },
    attribution:
      "The first line of the Analects (1.1), and therefore the most-quoted sentence in the Confucian corpus and the one most often detached from it. The three questions form a sequence that later commentary treats as a progression — learning alone, learning shared, learning unrecognised — so quoting only the first (“Is it not a pleasure to learn…”) drops the two stages that follow.",
    lastVerified: "2026-09-14",
  },

  Q0135: {
    original: {
      language: "Classical Chinese",
      text: "己所不欲，勿施於人。",
      note:
        "Eight characters. The English needs twice as many words because Chinese needs no subject, no tense, and no article; “what you do not want done to yourself” supplies all three.",
    },
    variants: [
      "Do not do unto others what you would not have them do unto you.",
      "Do not impose on others what you yourself do not desire.",
    ],
    attribution:
      "Analects 15.24, where it is Confucius' answer to Zigong's question about a single word to guide a whole life — the word given is shu, 恕, “consideration.” The same principle appears again at 12.2. It is the negative formulation of the golden rule, stated as a restraint rather than an injunction to act; the positive form (“do unto others…”) belongs to a different tradition and is not interchangeable with it.",
    lastVerified: "2026-09-14",
  },

  Q0136: {
    original: {
      language: "Classical Chinese",
      text: "知之為知之，不知為不知，是知也。",
      note:
        "Four clauses built on one repeated character, 知 (to know). The English has to alternate between “know” and “do not know” to reproduce a chiasmus Chinese produces by repetition.",
    },
    attribution:
      "Analects 2.17, addressed to Zilu. The structure is a definition by contrast: knowing is knowing when you know and knowing when you do not. It is often filed beside the Socratic profession of ignorance, but the move is different — Confucius is defining knowledge by accuracy about its own limits, not claiming to possess none.",
    lastVerified: "2026-09-14",
  },

  Q0140: {
    original: {
      language: "Classical Chinese",
      text: "朝聞道，夕死可矣。",
      note:
        "Literally: “In the morning hear the Way; at evening die — acceptable.” Eight characters, no subject. The English “one may die content” supplies a subject and an emotional state that the Chinese leaves to the reader.",
    },
    variants: [
      "If one hears the Way in the morning, one may die content that evening.",
      "If a man in the morning hears the truth, he may die in the evening without regret.",
    ],
    attribution:
      "Analects 4.8. The character 道 is rendered “the Way” here and “the truth” in several nineteenth-century translations — including the one that circulated most widely — and the two choices are not equivalent: 道 in the Analects is a course of conduct and a tradition, not a proposition that can be true. Readers searching the “truth” wording are usually looking at James Legge's rendering without knowing it.",
    lastVerified: "2026-09-14",
  },

  Q0144: {
    original: {
      language: "Classical Chinese",
      text: "知之者不如好之者，好之者不如樂之者。",
      note:
        "The repeated object is 之, a pronoun referring back to the Way. The English has to choose a noun for it, and the choice goes a long way toward deciding what the sentence seems to be about.",
    },
    variants: [
      "They who know the truth are not equal to those who love it.",
      "Those who know the truth are not equal to those who love it.",
      "The one who knows is not equal to the one who loves.",
    ],
    attribution:
      "Analects 6.20. The familiar English “they who know the truth” comes from a nineteenth-century translation that expanded the pronoun 之 into “the truth,” and the phrase then travelled as a freestanding aphorism — complete with the “they who” construction that belongs to Victorian English, not to Confucius. The original ranks three relations to the Way: knowing it, loving it, delighting in it. The third stage is the one Confucius puts highest, and it is the one the popular English version drops entirely.",
    lastVerified: "2026-09-14",
  },

  Q0175: {
    original: {
      language: "Chinese",
      text: "敬業與樂業",
      note:
        "The title of Liang Qichao's 1922 talk to students. The archive's English passage is a condensation of the talk's argument rather than a translation of one sentence, and it is marked as such with an ellipsis.",
    },
    attribution:
      "This is a speech, delivered at a school, and it has no single citable sentence behind the English rendering. Treating the condensed English as if it were a quotable line misrepresents its form: the interest of the passage is that Liang is arguing against the sharp division between work done for duty and work done for enjoyment, which is a position developed across a whole address.",
    lastVerified: "2026-09-14",
  },

  Q0183: {
    original: {
      language: "Latin",
      text: "Cum enim gratia non tollat naturam, sed perficiat.",
      note:
        "The sentence is subordinate in the Latin — “since grace does not destroy nature but perfects it” — inside a reply to an objection. The English rendering promotes it to a standalone assertion.",
    },
    variants: [
      "Grace does not destroy nature, but perfects it.",
      "Grace perfects nature.",
    ],
    attribution:
      "Summa Theologiae I, q.1, a.8, reply to the second objection, where Aquinas is answering the charge that theology should not use philosophy. The sentence is his justification for borrowing from pagan philosophers: grace completes the natural powers it finds rather than replacing them. Quoted as a standalone maxim about grace it loses that it is, in place, an argument about what theologians may take from Aristotle.",
    lastVerified: "2026-09-14",
  },

  Q0186: {
    original: {
      language: "English",
      text:
        "Whence has it all the materials of reason and knowledge? To this I answer, in one word, from experience.",
      note:
        "Seventeenth-century English, capitalised as Locke wrote it. The question is his own, put in order to be answered.",
    },
    attribution:
      "An Essay Concerning Human Understanding, II.i.2. The doctrine is routinely labelled “tabula rasa,” and that Latin phrase is not Locke's — it comes from earlier scholastic and Aristotelian usage. Locke's own image in the same chapter is “white paper.” The substitution matters because “blank slate” suggests an entirely passive mind, whereas the chapter's point is about the origin of ideas, not about the absence of innate powers.",
    lastVerified: "2026-09-14",
  },

  Q0196: {
    original: {
      language: "German",
      text: "Alles wirkliche Leben ist Begegnung.",
      note:
        "One sentence closing the first part of Ich und Du (1923). English translations diverge sharply: “All real living is meeting” and “All actual life is encounter” are the same German.",
    },
    variants: [
      "All real living is meeting.",
      "All actual life is encounter.",
    ],
    attribution:
      "The variance here is not a corruption but a genuine split in the English tradition of translating Buber, so two readers citing different renderings of the same German line can both be right about the source and disagree about the words. Buber means a specific kind of relation — the I–Thou encounter, which is not a meeting in the scheduling sense — and the plain English word “meeting” has drifted far from that since the translation was made.",
    lastVerified: "2026-09-14",
  },

  Q0197: {
    original: {
      language: "French",
      text: "L'attention est la forme la plus rare et la plus pure de la générosité.",
      note:
        "From a letter to the poet Joë Bousquet dated 13 April 1942. The archive keeps the date because the sentence has no printed source: it exists in Weil's correspondence.",
    },
    variants: [
      "Attention is the rarest and purest form of generosity.",
      "Attention is the purest and rarest form of generosity.",
      "Attention is the rarest form of generosity.",
    ],
    attribution:
      "Frequently misfiled as coming from Gravity and Grace or from Waiting for God, which were assembled and published after Weil's death. It comes from a letter, and the correspondent matters: Weil is writing to a wounded poet about what one person owes another's suffering, so “attention” here is a demanding discipline of self-emptying, not the everyday sense of the word. It is also sometimes attributed to Simone de Beauvoir on the strength of the shared first name.",
    lastVerified: "2026-09-14",
  },

  Q0330: {
    original: {
      language: "Latin",
      text:
        "Ego sum, ego existo, quoties a me profertur, vel mente concipitur, necessario esse verum.",
      note:
        "“I am, I exist — as often as it is uttered by me, or conceived in mind, it is necessarily true.” The English rendering trims the repeated “as often as” clause that makes the claim a claim about each occurrence.",
    },
    attribution:
      "Meditations II. This is the sentence Descartes actually wrote, and the reason the famous “cogito” formula is a summary rather than a quotation: the Meditations version states the necessary truth of the proposition each time it is thought, which is a stronger and more carefully guarded claim than “I think, therefore I am.”",
    lastVerified: "2026-09-14",
  },

  Q0432: {
    original: {
      language: "Latin",
      text: "Scientia et potentia humana in idem coincidunt.",
      note:
        "Literally “knowledge and human power coincide in the same thing.” The English renders coincidunt as “meet in one,” which keeps the sense of two things arriving at one point.",
    },
    variants: [
      "Knowledge is power.",
      "Human knowledge and human power meet in one.",
    ],
    attribution:
      "Novum Organum I, Aphorism 3. Bacon's aphorism continues: because the cause is unknown, the effect is lost. So he is not coining a slogan about education but stating a condition on action — you cannot produce an effect whose cause you have not found. The English tag “knowledge is power” is a much later and looser reduction of the sentence, and it is not Bacon's wording in any of his works.",
    lastVerified: "2026-09-14",
  },

  Q0436: {
    original: {
      language: "Ancient Greek",
      text: "ἡ ἀρετὴ μεσότης τις ἄρα ἐστίν.",
      note:
        "“Virtue, then, is a kind of mean.” The indefinite τις matters — “a kind of” — and the English tag “virtue lies in a mean” drops it.",
    },
    variants: [
      "Virtue lies in a mean.",
      "Virtue is the mean between two extremes.",
      "Moderation in all things.",
    ],
    attribution:
      "Nicomachean Ethics II.6, where the definition is immediately qualified: the mean is relative to the agent, not arithmetic, and a few lines later Aristotle adds that not every action admits one — there is no right amount of adultery or murder. “Moderation in all things” is not Aristotle and is close to the opposite of what the qualification says.",
    lastVerified: "2026-09-14",
  },

  Q0443: {
    original: {
      language: "French",
      text:
        "De tâcher toujours plutôt à me vaincre que la fortune, et à changer mes désirs que l'ordre du monde.",
      note:
        "The archive's English is a fragment of this clause: it keeps the second half and drops “to try always rather to overcome myself than fortune.”",
    },
    attribution:
      "Discourse on the Method, Part III. Quoted without its first half the line sounds like advice to accept circumstances; with it, the emphasis falls on self-mastery first and Stoic acceptance as the residue. This is one of the places where a half-quotation reverses the balance of a sentence.",
    lastVerified: "2026-09-14",
  },

  Q0395: {
    variants: [
      "I disapprove of what you say, but I will defend to the death your right to say it.",
      "I do not agree with what you have to say, but I'll defend to the death your right to say it.",
    ],
    attribution:
      "Not Voltaire. The sentence was written by Evelyn Beatrice Hall in her 1906 biography of Voltaire, under the pen name S. G. Tallentyre, as her own summary of his attitude. Voltaire's actual surviving writing on the subject is a 1770 letter to a correspondent containing a much blunter and narrower statement about the risks of persecution. Hall's sentence has been printed under Voltaire's name ever since, and the archive keeps it in the corpus flagged as a traditional attribution rather than presenting it as his wording.",
    lastVerified: "2026-09-14",
  },

  Q0314: {
    original: {
      language: "French",
      text: "Le doute n'est pas un état bien agréable, mais l'assurance est un état ridicule.",
      note:
        "“Doubt is not a very agreeable state, but assurance is a ridiculous one.” From a letter, not a published work.",
    },
    attribution:
      "The line comes from Voltaire's correspondence — a letter of November 1770 — rather than from the Philosophical Dictionary or any of the works usually cited for it. Like most of Voltaire's sharpest sentences it was written to one reader, which is why the phrasing is looser than his published prose.",
    lastVerified: "2026-09-14",
  },

  // --- Batch 2 (2026-09-27): next 25 by GSC impressions + source-intent ---

  Q0148: {
    original: {
      language: "Classical Chinese",
      text: "愛人者人恆愛之，敬人者人恆敬之。",
      note:
        "Eight characters in two parallel clauses. The archive's English opens with “Mencius said,” which is the dialogue frame from Lilou II, not part of the maxim itself; searchers looking for the reciprocity line usually drop that frame.",
    },
    variants: [
      "Those who love others are constantly loved by others; those who respect others are constantly respected by others.",
      "He who loves others is constantly loved by them; he who respects others is constantly respected by them.",
    ],
    attribution:
      "Mencius, Lilou II (離婁下). The reciprocity formula is Mencius' own; the archive's English includes the narrator's “Mencius said,” which belongs to the dialogue heading rather than to the saying. Quoting the framed version as a freestanding maxim makes the page title start with the author's name twice and hides the content a searcher is matching against.",
    lastVerified: "2026-09-27",
  },

  Q0362: {
    original: {
      language: "German",
      text: "Mit der Dummheit kämpfen Götter selbst vergebens.",
      note:
        "Literally “Against stupidity the gods themselves struggle in vain.” English usually softens kämpfen to “contend.”",
    },
    variants: [
      "Against stupidity the gods themselves contend in vain.",
      "Against stupidity even the gods struggle in vain.",
    ],
    attribution:
      "Schiller, Die Jungfrau von Orleans (The Maid of Orleans), Act III, Scene 6 — spoken by Talbot, not by Joan. Crediting it as a free-floating Schiller aphorism drops the dramatic speaker and the military defeat that prompts the line.",
    lastVerified: "2026-09-27",
  },

  Q0346: {
    original: {
      language: "English",
      text: "The art of being wise is the art of knowing what to overlook.",
      note:
        "From Principles of Psychology, Chapter XXII (“Reasoning”), where James is discussing selective attention in inference, not offering a lifestyle tip about ignoring people.",
    },
    attribution:
      "William James, The Principles of Psychology (1890), Chapter XXII. The surrounding argument is about what a reasoner must leave out in order to form a conclusion; circulating the sentence as general advice about “not sweating the small stuff” strips the cognitive claim that made it worth writing.",
    lastVerified: "2026-09-27",
  },

  Q0005: {
    original: {
      language: "Ancient Greek",
      text: "τὸ τὰ αὑτοῦ πράττειν καὶ μὴ πολυπραγμονεῖν δικαιοσύνη ἐστί.",
      note:
        "“Doing one's own things and not being a busybody is justice.” The archive's English compresses πολυπραγμονεῖν to “not meddling in others’.”",
    },
    variants: [
      "Justice is doing one's own work and not meddling in others'.",
      "Justice is minding one's own business.",
    ],
    attribution:
      "Plato, Republic IV 433a–b, where justice in the city is defined as each class doing its own work. The popular shortening “justice is minding one's own business” loses the institutional claim and reads as personal etiquette.",
    lastVerified: "2026-09-27",
  },

  Q0073: {
    original: {
      language: "German",
      text: "Der Mensch ist etwas, das überwunden werden soll.",
      note:
        "“Man is something that shall be overcome.” From Zarathustra's prologue; the verb is sollen, a requirement, not a prediction.",
    },
    variants: [
      "Man is something that shall be overcome.",
      "Man is something to be surpassed.",
    ],
    attribution:
      "Nietzsche, Also sprach Zarathustra, Prologue §3. The speaker is Zarathustra addressing the marketplace crowd about the Übermensch; quoting it as Nietzsche's bare definition of humanity without that frame turns a prophetic demand into a slogan about self-improvement.",
    lastVerified: "2026-09-27",
  },

  Q0019: {
    original: {
      language: "Ancient Greek",
      text: "τὸ φρικωδέστατον οὖν τῶν κακῶν ὁ θάνατος οὐθὲν πρὸς ἡμᾶς.",
      note:
        "Epicurus' letter argues that death “is nothing to us” because sensation ends with dissolution. The archive's English keeps the argument's middle step (“what has been dissolved has no sensation”).",
    },
    variants: [
      "Death is nothing to us.",
      "Death is nothing to us; when we are, death is not; when death is, we are not.",
    ],
    attribution:
      "Epicurus, Letter to Menoeceus. The shorter maxim “Death is nothing to us” is Epicurus' own opening claim; the two-clause expansion often printed beside it (“when we are, death is not…”) is a later didactic paraphrase of the same argument, not a second sentence from the letter.",
    lastVerified: "2026-09-27",
  },

  Q0051: {
    original: {
      language: "French",
      text: "Que philosopher c'est apprendre à mourir.",
      note:
        "Montaigne's chapter title and thesis: to philosophize is to learn how to die. He is reframing Cicero, not inventing the claim.",
    },
    variants: [
      "To philosophize is to learn how to die.",
      "To philosophise is to learn to die.",
    ],
    attribution:
      "Montaigne, Essais I.20 (“Que philosopher c'est apprendre à mourir”). He explicitly credits Cicero's Tusculan Disputations for the formula; presenting it as Montaigne's original insight without that debt misstates both the chapter and the tradition it continues.",
    lastVerified: "2026-09-27",
  },

  Q0093: {
    original: {
      language: "German",
      text:
        "Dem Menschen kann alles genommen werden, nur nicht eines: die letzte der menschlichen Freiheiten — unter welchen Umständen auch immer die eigene Einstellung zu wählen, seinen eigenen Weg.",
      note:
        "Frankl wrote in German; the widely quoted English is the standard translation of Man's Search for Meaning. Wording varies slightly by edition of the English text.",
    },
    variants: [
      "Everything can be taken from a man but one thing: the last of the human freedoms — to choose one's attitude in any given set of circumstances.",
      "The last of the human freedoms is to choose one's attitude in any given set of circumstances.",
    ],
    attribution:
      "Viktor Frankl, Man's Search for Meaning (originally …trotzdem Ja zum Leben sagen). The line belongs to his account of camp experience and logotherapy's claim about attitude; clipping it to “choose your attitude” without the “last freedom” framing turns a claim forged under extremity into generic positivity.",
    lastVerified: "2026-09-27",
  },

  Q0336: {
    original: {
      language: "English",
      text: "Reason is, and ought only to be the slave of the passions, and can never pretend to any other office than to serve and obey them.",
      note:
        "The archive quotes the first clause; Hume's full sentence adds the office reason may claim. Cutting the second half makes the claim sound wilder than the paragraph argues.",
    },
    variants: [
      "Reason is, and ought only to be the slave of the passions.",
      "Reason is the slave of the passions.",
    ],
    attribution:
      "Hume, A Treatise of Human Nature II.3.3. He is denying that reason alone can motivate action, not recommending passion over thought. The truncated “reason is the slave of the passions” is the version that circulates as a slogan against rationality.",
    lastVerified: "2026-09-27",
  },

  Q0181: {
    original: {
      language: "Ancient Greek",
      text: "πάντων χρημάτων μέτρον ἐστὶν ἄνθρωπος.",
      note:
        "“Of all things the measure is man.” Survives as a fragment (DK 80B1) quoted by Plato in the Theaetetus; we do not have Protagoras' own book.",
    },
    variants: [
      "Man is the measure of all things.",
      "Of all things the measure is man.",
    ],
    attribution:
      "Protagoras DK 80B1, preserved through Plato's Theaetetus 152a. Plato immediately presses the fragment into a relativist reading about perception; whether Protagoras meant that, or something narrower about human standards of judgment, is exactly the dispute the dialogue stages. Quoting the English alone as a finished doctrine skips that problem.",
    lastVerified: "2026-09-27",
  },

  Q0348: {
    original: {
      language: "English",
      text:
        "Three passions, simple but overwhelmingly strong, have governed my life: the longing for love, the search for knowledge, and unbearable pity for the suffering of mankind.",
      note:
        "Opening of the prologue to Russell's Autobiography. The three passions structure the pages that follow; quoting only the first passion loses the triad.",
    },
    attribution:
      "Bertrand Russell, Autobiography, Prologue. This is Russell speaking in his own late voice about his life, not a line from Principia Mathematica or the popular essays. Sites that cite “The Conquest of Happiness” or no source at all are usually copying each other.",
    lastVerified: "2026-09-27",
  },

  Q0127: {
    original: {
      language: "German",
      text: "Die Bedeutung eines Wortes ist sein Gebrauch in der Sprache.",
      note:
        "Philosophical Investigations §43. English standard: “the meaning of a word is its use in the language.”",
    },
    variants: [
      "The meaning of a word is its use in the language.",
      "Meaning is use.",
    ],
    attribution:
      "Wittgenstein, Philosophical Investigations §43. “Meaning is use” is a classroom compression, not a sentence he wrote; the §43 wording is about the meaning of a word in many cases, with an explicit hedge Wittgenstein's sloganized version drops.",
    lastVerified: "2026-09-27",
  },

  Q0023: {
    original: {
      language: "Ancient Greek / English tradition",
      text: "ταράσσει τοὺς ἀνθρώπους οὐ τὰ πράγματα, ἀλλὰ τὰ περὶ τῶν πραγμάτων δόγματα.",
      note:
        "Enchiridion 5. English often says “judgments” or “opinions” for δόγματα — both are defensible; “things” for πράγματα keeps the Stoic contrast between externals and assents.",
    },
    variants: [
      "It is not things that disturb people, but their judgments about things.",
      "Men are disturbed not by things, but by the views which they take of them.",
    ],
    attribution:
      "Epictetus, Enchiridion 5 (via Arrian). The Elizabethan-sounding “Men are disturbed not by things…” is a common older English rendering of the same Greek; both point to the same section. Crediting Marcus Aurelius is a frequent mix-up driven by Meditations' popularity, not by the text.",
    lastVerified: "2026-09-27",
  },

  Q0101: {
    original: {
      language: "Ancient Greek",
      text:
        "μὴ ζήτει τὰ γινόμενα γίνεσθαι ὡς θέλεις, ἀλλὰ θέλε τὰ γινόμενα ὡς γίνεται, καὶ εὐροήσεις.",
      note:
        "Enchiridion 8. “Flow well” (εὐροήσεις) is the Stoic goal-word; some English versions say “you will have a serene life” instead.",
    },
    variants: [
      "Do not seek for things to happen as you wish, but wish for things to happen as they do.",
      "Don't demand that things happen as you wish, but wish that they happen as they do.",
    ],
    attribution:
      "Epictetus, Enchiridion 8. Closely related advice appears in the Discourses; the numbered Handbook form is the one most citation pages mean. Pairing it with Marcus Aurelius without a locator is the usual aggregator error.",
    lastVerified: "2026-09-27",
  },

  Q0448: {
    original: {
      language: "German",
      text:
        "Jeder hält die Grenze seines Gesichtskreises für die Grenze der Welt.",
      note:
        "From Parerga und Paralipomena. English “field of vision” renders Gesichtskreis; some versions say “horizon.”",
    },
    variants: [
      "Everyone takes the limits of his own field of vision for the limits of the world.",
      "Every man takes the limits of his own field of vision for the limits of the world.",
    ],
    attribution:
      "Schopenhauer, Parerga and Paralipomena (usually cited from the “Psychological Observations” / related aphoristic sections). It is not from The World as Will and Representation; sites that cite WWR are recycling a wrong default title for Schopenhauer.",
    lastVerified: "2026-09-27",
  },

  Q0259: {
    original: {
      language: "German",
      text: "Was vernünftig ist, das ist wirklich; und was wirklich ist, das ist vernünftig.",
      note:
        "Preface to the Philosophy of Right. English “actual” for wirklich is the standard philosophical choice; “real” invites a cruder reading Hegel spent the preface blocking.",
    },
    variants: [
      "What is rational is actual; and what is actual is rational.",
      "The real is rational and the rational is real.",
    ],
    attribution:
      "Hegel, Elements of the Philosophy of Right, Preface (1820). The sloganized “the real is rational” is the version critics attacked; Hegel's wirklich is “actual” in the sense of what has developed into its concept, not “whatever happens to exist.” Quoting the English without that distinction is how the line became a caricature of apologetics.",
    lastVerified: "2026-09-27",
  },

  Q0397: {
    original: {
      language: "German",
      text: "Zwei Seelen wohnen, ach! in meiner Brust.",
      note:
        "Faust I, “Before the City Gate.” Faust speaks of two souls; English “alas” for ach is conventional.",
    },
    variants: [
      "Two souls, alas, are dwelling in my breast.",
      "Two souls dwell, alas, in my breast.",
    ],
    attribution:
      "Goethe, Faust I. Spoken by Faust about the pull between earthly desire and ascent to higher worlds — not a generic confession of indecision. Detaching it from Faust's speech makes it a personality type instead of a dramatic beat.",
    lastVerified: "2026-09-27",
  },

  Q0261: {
    original: {
      language: "English",
      text: "To be great is to be misunderstood.",
      note:
        "From “Self-Reliance” (1841). Emerson lists misunderstood great figures immediately before and after; the sentence is a hinge, not a free-standing boast.",
    },
    attribution:
      "Emerson, “Self-Reliance,” in Essays: First Series. Circulating it as permission to ignore criticism without Emerson's surrounding list (Pythagoras, Socrates, Jesus, Luther, Copernicus, Galileo, Newton) turns a historical observation into a motivational sticker.",
    lastVerified: "2026-09-27",
  },

  Q0080: {
    original: {
      language: "English",
      text:
        "Habit is the enormous fly-wheel of society, its most precious conservative agent.",
      note:
        "Principles of Psychology, chapter on Habit. James' next sentences explain why habit keeps social order from dissolving daily.",
    },
    attribution:
      "William James, The Principles of Psychology, “Habit.” Often misfiled under Talks to Teachers or popular self-help redactionsitions. The fly-wheel metaphor is James' own; the surrounding chapter is about neural pathways and social continuity, not productivity tips.",
    lastVerified: "2026-09-27",
  },

  Q0439: {
    original: {
      language: "Ancient Greek",
      text:
        "γεγόναμεν γὰρ πρὸς συνεργίαν ὡς πόδες, ὡς χεῖρες, ὡς βλέφαρα, ὡς οἱ στοῖχοι τῶν ἄνω καὶ κάτω ὀδόντων.",
      note:
        "Meditations XI.18. The archive stops after eyelids; the Greek continues with rows of upper and lower teeth.",
    },
    variants: [
      "We are made for cooperation, like feet, like hands, like eyelids.",
      "We were born to work together like feet, hands, and eyes.",
    ],
    attribution:
      "Marcus Aurelius, Meditations XI.18. Same family of images as VI.54 (the swarm/bee), but a different book and a fuller list of body parts. Citing “Meditations” without a book number collapses distinct passages into one.",
    lastVerified: "2026-09-27",
  },

  Q0304: {
    original: {
      language: "Classical Chinese",
      text: "隨處作主，立處皆真。",
      note:
        "Record of Linji. English expansions (“wherever you are, make yourself master…”) supply subjects and verbs the Chinese leaves compact.",
    },
    variants: [
      "Wherever you are, make yourself master; wherever you stand is real.",
      "Be master wherever you are; wherever you stand is the true place.",
    ],
    attribution:
      "Linji Yixuan, Record of Linji (臨濟錄). A Rinzai teaching on autonomy of mind, not a travel slogan. Attributing it to a generic “Zen proverb” without Linji is how aggregator pages lose the only checkable locator.",
    lastVerified: "2026-09-27",
  },

  Q0393: {
    original: {
      language: "English",
      text:
        "Being all equal and independent, no one ought to harm another in his life, health, liberty, or possessions.",
      note:
        "Second Treatise of Government §6. Locke's state-of-nature law of nature; the list of protected goods is the sentence's point.",
    },
    attribution:
      "Locke, Second Treatise of Government, Chapter II §6. Often shortened to “life, liberty, and property,” which is Locke's vocabulary elsewhere and in later political reception — but this sentence's wording is “life, health, liberty, or possessions.” Swapping in Jefferson's later triad mis-cites both texts.",
    lastVerified: "2026-09-27",
  },

  Q0423: {
    original: {
      language: "German",
      text: "Denk nicht, sondern schau!",
      note:
        "Philosophical Investigations §66, in the discussion of games and family resemblance. English “Don’t think, but look!” is the standard Anscombe/Rhees rendering.",
    },
    variants: [
      "Don’t think, but look!",
      "Don't think, look!",
    ],
    attribution:
      "Wittgenstein, Philosophical Investigations §66. Imperative addressed to someone tempted to assume a single essence of “game.” Quoting it as a general anti-intellectual motto detaches it from the method of looking at cases that the section teaches.",
    lastVerified: "2026-09-27",
  },

  Q0258: {
    original: {
      language: "German",
      text:
        "Das Selbstbewußtsein erreicht seine Befriedigung nur in einem anderen Selbstbewußtsein.",
      note:
        "Phenomenology of Spirit, Chapter IV A (Independence and Dependence of Self-Consciousness: Lordship and Bondage). English “attains its satisfaction” is the usual Miller/Baillie range.",
    },
    attribution:
      "Hegel, Phenomenology of Spirit IV.A — the opening of the struggle for recognition that leads into the lord–bondsman dialectic. Citing only “Hegel on recognition” without the chapter leaves a searcher in a 600-page book with no locator.",
    lastVerified: "2026-09-27",
  },

  Q0335: {
    original: {
      language: "English",
      text:
        "Let us then suppose the mind to be, as we say, white paper, void of all characters, without any ideas.",
      note:
        "Essay Concerning Human Understanding II.1.2. “White paper” is Locke's phrase; later Latin branding as tabula rasa is the tradition's label for the same claim.",
    },
    variants: [
      "The mind is a white paper, void of all characters.",
      "The mind is a blank slate.",
    ],
    attribution:
      "Locke, Essay Concerning Human Understanding II.1.2. “Blank slate” / tabula rasa is the later handbook name; Locke's English is “white paper.” Quoting “blank slate” as Locke's words is a paraphrase of the metaphor, not a citation of his sentence.",
    lastVerified: "2026-09-27",
  },

  Q0415: {
    original: {
      language: "Chinese",
      text:
        "少年智則國智，少年富則國富，少年強則國強。",
      note:
        "From Liang Qichao's “On the Young China” (少年中國說). The archive's English expands three parallel clauses; Chinese is denser.",
    },
    variants: [
      "If the youth are wise, the nation is wise; if the youth are strong, the nation is strong.",
      "The wisdom of youth is the wisdom of the nation.",
    ],
    attribution:
      "Liang Qichao, “On the Young China” (1900). A late-Qing reform essay, not a classical Confucian line. Crediting Confucius or an anonymous “Chinese proverb” is the usual misattribution when the English circulates without Liang's name.",
    lastVerified: "2026-09-27",
  },

  Q0283: {
    original: {
      language: "Classical Chinese",
      text: "萬物皆備於我矣。反身而誠，樂莫大焉。",
      note:
        "Mencius, Jinxin I. Two sentences: all things are complete in me; turning within to find sincerity is the greatest delight.",
    },
    attribution:
      "Mencius, Jinxin I (盡心上). Neo-Confucian readers made this a metaphysical claim about the mind's completeness; Mencius' immediate context is moral self-examination. Quoting only the first sentence (“all things are complete in me”) without 反身而誠 loses the practice the delight is tied to.",
    lastVerified: "2026-09-27",
  },
};

/**
 * Quotes whose source-forward metadata has been reviewed against the cited
 * edition. Batch 1 is the top-impression and top-ranking set: the five
 * long-tails that have already reached positions 1–3, plus the pages carrying
 * the largest impression counts in Search Console.
 *
 * The batches are recorded so the rollout stays visible and incremental. A
 * site-wide metadata rewrite is a batch-rewrite signal, and a batch-rewrite
 * signal is what invited the August re-evaluation; fifty reviewed pages a week
 * is deliberate, not an unfinished job.
 */
export const VERIFICATION_BATCHES: Record<string, string[]> = {
  "batch-1-2026-09-14": [
    "Q0001",
    "Q0002",
    "Q0003",
    "Q0004",
    "Q0032",
    "Q0054",
    "Q0055",
    "Q0059",
    "Q0062",
    "Q0070",
    "Q0071",
    "Q0072",
    "Q0074",
    "Q0102",
    "Q0120",
    "Q0134",
    "Q0135",
    "Q0136",
    "Q0140",
    "Q0144",
    "Q0175",
    "Q0183",
    "Q0186",
    "Q0196",
    "Q0197",
    "Q0330",
    "Q0395",
    "Q0432",
    "Q0436",
    "Q0443",
    "Q0314",
  ],
  "batch-2-2026-09-27": [
    "Q0148",
    "Q0362",
    "Q0346",
    "Q0005",
    "Q0073",
    "Q0019",
    "Q0051",
    "Q0093",
    "Q0336",
    "Q0181",
    "Q0348",
    "Q0127",
    "Q0023",
    "Q0101",
    "Q0448",
    "Q0259",
    "Q0397",
    "Q0261",
    "Q0080",
    "Q0439",
    "Q0304",
    "Q0393",
    "Q0423",
    "Q0258",
    "Q0335",
    "Q0415",
    "Q0283",
  ],
};

const batchIds = new Set(Object.values(VERIFICATION_BATCHES).flat());

export function isInVerificationBatch(id: string) {
  return batchIds.has(id.toUpperCase());
}

export function verificationNote(id: string) {
  return quoteVerification[id.toUpperCase()];
}

/**
 * The two dates the corpus itself last moved, used as the fallback “last
 * verified” for passages with no per-quote register entry.
 *
 * They are different on purpose. Q0001–Q0499 with no written commentary have
 * not changed since the corpus stabilised on 2026-08-26. The later quotations,
 * and the legacy passages that received passage-specific commentary, were
 * written on 2026-08-30. Stamping one date on all of them would tell a crawler
 * that nine hundred pages changed on the same day, which is the exact signal
 * the sitemap work exists to stop sending.
 */
export const LEGACY_CORPUS_DATE = "2026-08-26";
export const CORPUS_UNLOCK_DATE = "2026-08-30";

export function corpusReviewDate(id: string, hasOwnCommentary: boolean) {
  const numeric = Number(id.replace(/^Q/i, ""));
  if (Number.isFinite(numeric) && numeric > 499) return CORPUS_UNLOCK_DATE;
  return hasOwnCommentary ? CORPUS_UNLOCK_DATE : LEGACY_CORPUS_DATE;
}

/**
 * ISO 639 codes for the languages recorded above, so the structured data can
 * state the language of the original rather than only naming it in prose.
 * Deliberately partial: an entry missing here means the language is either a
 * pair (“Latin and French”) or too uncertain to assert, and the schema simply
 * omits the field rather than guessing a code.
 */
export const LANGUAGE_CODES: Record<string, string> = {
  "Ancient Greek": "grc",
  Latin: "la",
  French: "fr",
  German: "de",
  "Classical Chinese": "lzh",
  Chinese: "zh",
  Pali: "pi",
  English: "en",
  "Koine Greek": "grc",
  Danish: "da",
};

export function languageCode(language: string) {
  return LANGUAGE_CODES[language];
}
