/**
 * Per-quotation verification register.
 *
 * Search Console shows this archive's only top-3 rankings all sit in the
 * "quote source" family: readers arrive holding a sentence, a name, or a
 * fragment, and they want the locator. The pages that rank for those queries
 * are the ones that answer attribution questions explicitly instead of only
 * presenting the passage.
 *
 * This register holds the material that answer needs and that no scraper site
 * has: the original-language wording where a single original exists, the
 * variants that circulate in place of it, and the specific thing readers get
 * wrong about who said it and in what sense.
 *
 * Deliberately a register, not a template. Nothing here is generated by
 * pattern: an entry exists only where there is something true and specific to
 * say. Pages without an entry render the citation block alone rather than
 * filler, because a boilerplate paragraph repeated across 690 pages is the
 * exact thin-content signature that triggered the August quality re-evaluation.
 *
 * Adding a batch: append entries, then add the IDs to VERIFICATION_BATCHES.
 */

export type VerificationNote = {
  /** The wording in the language the author wrote, when one original exists. */
  original?: {
    language: string;
    text: string;
    /** What the rendering into English added, dropped, or decided. */
    note?: string;
  };
  /** Wording that circulates in place of the cited text, and why it differs. */
  variants?: string[];
  /** Who gets credited wrongly, where the line really sits, and what it means. */
  attribution: string;
  /** Date this record was last checked against the cited edition. */
  lastVerified: string;
};

export const quoteVerification: Record<string, VerificationNote> = {
  Q0001: {
    original: {
      language: "Ancient Greek",
      text: "ὁ δὲ ἀνεξέταστος βίος οὐ βιωτὸς ἀνθρώπῳ.",
      note:
        "The Greek word order is “the unexamined life, not to be lived, for a human being.” Most English versions drop “for a human being,” which is where the claim is limited to a human life and not to life as such.",
    },
    variants: [
      "The unexamined life is not worth living.",
      "An unexamined life is not worth living.",
    ],
    attribution:
      "Socrates wrote nothing. This is Plato's rendering of Socrates' speech in the Apology, and the line falls in the penalty phase after the guilty verdict — Socrates is refusing a sentence of silence, not offering a maxim about self-help. Quoting it as a general exhortation to reflection drops the occasion it was spoken on.",
    lastVerified: "2026-09-14",
  },

  Q0002: {
    original: {
      language: "Ancient Greek",
      text: "ἃ μὴ οἶδα οὐδὲ οἴομαι εἰδέναι.",
      note:
        "Literally “what I do not know, I do not think I know either.” The archive's English rendering compresses this to a claim about claimed knowledge.",
    },
    variants: [
      "I know that I know nothing.",
      "I know one thing: that I know nothing.",
    ],
    attribution:
      "“I know that I know nothing” is a later compression, not a sentence in Plato. The Apology passage is narrower and more careful: Socrates claims only that where he lacks knowledge he also does not believe he has it. The popular version turns a claim about his own position into a paradox about knowledge in general.",
    lastVerified: "2026-09-14",
  },

  Q0003: {
    original: {
      language: "Ancient Greek",
      text: "βούλομαι μᾶλλον ἀδικεῖσθαι ἢ ἀδικεῖν.",
      note:
        "“I would rather be wronged than do wrong.” The English noun-form rendering (“it is worse to do injustice than to suffer it”) converts Socrates' stated preference into a ranked claim that the interlocutor Polus immediately contests.",
    },
    attribution:
      "Said by Socrates in the Gorgias, at 469b–c, and it is an argued conclusion rather than an aphorism: Polus finds it absurd and the rest of the dialogue is Socrates defending it. The line is often lifted out of that exchange and quoted as received wisdom, which loses that it was the controversial position.",
    lastVerified: "2026-09-14",
  },

  Q0004: {
    original: {
      language: "Ancient Greek",
      text: "οὐδεὶς ἑκὼν ἁμαρτάνει.",
      note:
        "“No one errs willingly.” Also stated near the end of the Gorgias (509e), which matters because the Protagoras passage is where the argument is built, not where it is first asserted.",
    },
    attribution:
      "One of the two claims usually labelled the Socratic paradoxes — the other being that virtue is knowledge. Read on its own it sounds like a denial of responsibility; in context it follows from the premise that everyone acts toward what they believe good, so acting badly is a failure of belief rather than of will.",
    lastVerified: "2026-09-14",
  },

  Q0032: {
    original: {
      language: "Latin",
      text: "Non est ad astra mollis e terris via.",
      note:
        "Word for word: “there is no soft road from the earth to the stars.” The adjective is mollis — soft, yielding, easy to tread — and most English versions render it “easy,” which keeps the sense but loses the tactile contrast with the hard road.",
    },
    variants: [
      "There is no easy way from the earth to the stars.",
      "To the stars through difficulties.",
      "Per aspera ad astra.",
    ],
    attribution:
      "The line is from Seneca's tragedy Hercules Furens, at verse 437 — a play, not the Letters to Lucilius where most circulating Seneca quotations originate, and the two are constantly confused. It is also routinely merged with “per aspera ad astra,” a separate Latin motto that is not in Seneca and whose wording is later. The play's line is spoken inside the drama and carries the dramatic situation with it; the film-poster version has shed all of that.",
    lastVerified: "2026-09-14",
  },

  Q0054: {
    original: {
      language: "Latin and French",
      text: "Ego cogito, ergo sum.",
      note:
        "The Latin appears in the Principles of Philosophy I, §7. The French original of the same thought is “Je pense, donc je suis,” in the Discourse on the Method IV. The three-word tag “cogito ergo sum” is a compression of the Latin, not a quotation in either text.",
    },
    variants: ["Cogito ergo sum.", "I think, therefore I am (I exist)."],
    attribution:
      "In the Meditations Descartes does not use the famous formula at all; he writes “Ego sum, ego existo” (I am, I exist) at the second Meditation. Passing the “cogito” off as the Meditations wording confuses the work where the argument is made with the works where Descartes summarised it.",
    lastVerified: "2026-09-14",
  },

  Q0055: {
    original: {
      language: "Latin",
      text:
        "Semel in vita de omnibus, quantum fieri potest, esse dubitandum.",
      note:
        "“Once in a life, as far as possible, everything must be doubted.” The words “once in a lifetime” carry the whole method: this is a single act of demolition, not a standing policy.",
    },
    attribution:
      "The sentence is Descartes' statement of the method of the first Meditation. It is routinely recited as a general endorsement of scepticism, which inverts it: Descartes doubts once in order to find something that cannot be doubted, and the point of the exercise is the foundation he reaches at the end of the second Meditation.",
    lastVerified: "2026-09-14",
  },

  Q0059: {
    original: {
      language: "French",
      text: "Le cœur a ses raisons que la raison ne connaît point.",
      note:
        "The archive cites the Brunschvicg numbering. The Pensées are numbered differently in the Lafuma and Sellier editions, so the section number will not match a source that uses a different scheme — a real hazard for anyone trying to check the line.",
    },
    attribution:
      "The French is usually mistranslated as “the heart has reasons that reason cannot know,” which makes it a rejection of reason. The French says reason does not know them, not that they are unknowable — the heart's reasons are ones the discursive intellect has not reached. Pascal's target is the theology of his own century, not reason as such.",
    lastVerified: "2026-09-14",
  },

  Q0062: {
    original: {
      language: "French",
      text: "L'homme est né libre, et partout il est dans les fers.",
      note:
        "The French noun is the same word for chains and for fetters; “in chains” loses that the image is specifically of slave irons.",
    },
    attribution:
      "This is the opening sentence of On the Social Contract I.1. Because it works as a standalone lament it is read as Rousseau announcing a fixed condition, whereas the sentence opens a book whose point is that the chains were made and can be unmade — the “problem” he names in I.1 is to find a legitimate form of association, not to mourn an unavoidable loss of freedom.",
    lastVerified: "2026-09-14",
  },

  Q0070: {
    original: {
      language: "German",
      text: "Aus der Kriegsschule des Lebens. — Was mich nicht umbringt, macht mich stärker.",
      note:
        "The German has two parts. The first, “From the military school of life,” is a heading Nietzsche gives the aphorism; the second is the sentence everyone quotes.",
    },
    variants: [
      "What does not kill me makes me stronger.",
      "That which does not kill us makes us stronger.",
    ],
    attribution:
      "The plural “us” is the most common alteration of the German, which is first-person singular (“mich”). It sits in Twilight of the Idols among the thirty-eight “Maxims and Arrows,” which is to say in a work of compressed polemic rather than a statement of doctrine, and Nietzsche does not gloss it anywhere.",
    lastVerified: "2026-09-14",
  },

  Q0071: {
    original: {
      language: "Latin",
      text: "Amor fati.",
      note:
        "Latin, coined as a phrase rather than quoted from an earlier author. The German sentence it sits in is “Amor fati: das sei von nun an meine Liebe!”",
    },
    attribution:
      "“Amor fati” is Nietzsche's own formulation in The Gay Science §276 — it is not a Stoic term of art, however frequently it is filed under Stoicism. Epictetus and Marcus Aurelius counsel acceptance of what is not in our control; Nietzsche's love of fate also wills that the past have been exactly as it was, which is a heavier demand and connects to the eternal recurrence shortly after.",
    lastVerified: "2026-09-14",
  },

  Q0072: {
    original: {
      language: "German",
      text: "Wie man wird, was man ist.",
      note:
        "The subtitle of Ecce Homo. The thought is older than the book — Nietzsche credits Pindar, whose second Pythian ode has “become such as you are, having learned what that is.”",
    },
    variants: ["Become what you are.", "How one becomes what one is."],
    attribution:
      "“Become what you are” usually reaches readers through Pindar or through the English title of the Ecce Homo subtitle, and it is then read as an encouragement to self-expression. In Nietzsche the phrase is about the long, unfree process by which a person's disparate drives are disciplined into a single style — the becoming is not willed, it is survived.",
    lastVerified: "2026-09-14",
  },

  Q0074: {
    original: {
      language: "German",
      text:
        "Dieses Leben, wie du es jetzt lebst und gelebt hast, wirst du noch einmal und noch unzählige Male leben müssen.",
      note:
        "The demon's speech in The Gay Science §341. The English rendering preserves the sentence break, which is what makes the passage overwhelming.",
    },
    variants: [
      "What if a demon told you this life would repeat endlessly?",
      "Eternal recurrence.",
    ],
    attribution:
      "This is the thought experiment of the eternal recurrence — and in §341 it is a demon's speech whose purpose is a test, closing with the question of whether you could want it. Readers often present the recurrence as Nietzsche's cosmology, a claim about how the universe actually runs; in The Gay Science it is a condition posed to a single reader, and the later notes in which he took it more literally are a different and much cruder form of the idea.",
    lastVerified: "2026-09-14",
  },

  Q0102: {
    original: {
      language: "Ancient Greek",
      text: "τὸ τῇ μέλισσῃ μὴ συμφέρον οὐδὲ τῷ συμμέλει συμφέρει.",
      note:
        "The Greek second noun is συμμέλει, the swarm. The standard English rendering says “hive,” which names the structure rather than the colony.",
    },
    variants: [
      "What is not good for the hive is not good for the bee.",
      "What is not beneficial to the swarm is not beneficial to the bee.",
      "What is not good for the swarm is not good for the bee.",
    ],
    attribution:
      "Meditations VI.54, where the sentence belongs to Marcus Aurelius' argument that he was made for the whole and cannot act against it. The image is a swarm — a body that the individual bee physically cannot survive leaving — and the popular English substitution of “hive” bends it toward a claim about institutions and conformity, which is the opposite of the Stoic point about natural membership.",
    lastVerified: "2026-09-14",
  },

  Q0120: {
    original: {
      language: "English",
      text: "Truth happens to an idea. It becomes true, is made true by events.",
      note:
        "Two sentences, from Lecture VI, “Pragmatism's Conception of Truth,” in Pragmatism (1907). The second sentence is what the first means.",
    },
    variants: [
      "Truth happens to an idea.",
      "Truth is what happens to an idea.",
    ],
    attribution:
      "Quoted at the first sentence alone it reads as relativism — as if anything could become true. James' argument is the opposite: an idea is made true by its verification in events, so the second sentence is not an elaboration but the claim itself. Cutting it off is the single most common way this passage is misrepresented, and readers who arrive looking for the source are usually looking because the one-sentence version seemed to say something James would have denied.",
    lastVerified: "2026-09-14",
  },

  Q0134: {
    original: {
      language: "Classical Chinese",
      text:
        "學而時習之，不亦說乎？有朋自遠方來，不亦樂乎？人不知而不慍，不亦君子乎？",
      note:
        "Three rhetorical questions opening the Analects. The archive's rendering expands each into English clause order; the Chinese is far more compact.",
    },
    attribution:
      "The first line of the Analects (1.1), and therefore the most-quoted sentence in the Confucian corpus and the one most often detached from it. The three questions form a sequence that later commentary treats as a progression — learning alone, learning shared, learning unrecognised — so quoting only the first (“Is it not a pleasure to learn…”) drops the two stages that follow.",
    lastVerified: "2026-09-14",
  },

  Q0135: {
    original: {
      language: "Classical Chinese",
      text: "己所不欲，勿施於人。",
      note:
        "Eight characters. The English needs twice as many words because Chinese needs no subject, no tense, and no article; “what you do not want done to yourself” supplies all three.",
    },
    variants: [
      "Do not do unto others what you would not have them do unto you.",
      "Do not impose on others what you yourself do not desire.",
    ],
    attribution:
      "Analects 15.24, where it is Confucius' answer to Zigong's question about a single word to guide a whole life — the word given is shu, 恕, “consideration.” The same principle appears again at 12.2. It is the negative formulation of the golden rule, stated as a restraint rather than an injunction to act; the positive form (“do unto others…”) belongs to a different tradition and is not interchangeable with it.",
    lastVerified: "2026-09-14",
  },

  Q0136: {
    original: {
      language: "Classical Chinese",
      text: "知之為知之，不知為不知，是知也。",
      note:
        "Four clauses built on one repeated character, 知 (to know). The English has to alternate between “know” and “do not know” to reproduce a chiasmus Chinese produces by repetition.",
    },
    attribution:
      "Analects 2.17, addressed to Zilu. The structure is a definition by contrast: knowing is knowing when you know and knowing when you do not. It is often filed beside the Socratic profession of ignorance, but the move is different — Confucius is defining knowledge by accuracy about its own limits, not claiming to possess none.",
    lastVerified: "2026-09-14",
  },

  Q0140: {
    original: {
      language: "Classical Chinese",
      text: "朝聞道，夕死可矣。",
      note:
        "Literally: “In the morning hear the Way; at evening die — acceptable.” Eight characters, no subject. The English “one may die content” supplies a subject and an emotional state that the Chinese leaves to the reader.",
    },
    variants: [
      "If one hears the Way in the morning, one may die content that evening.",
      "If a man in the morning hears the truth, he may die in the evening without regret.",
    ],
    attribution:
      "Analects 4.8. The character 道 is rendered “the Way” here and “the truth” in several nineteenth-century translations — including the one that circulated most widely — and the two choices are not equivalent: 道 in the Analects is a course of conduct and a tradition, not a proposition that can be true. Readers searching the “truth” wording are usually looking at James Legge's rendering without knowing it.",
    lastVerified: "2026-09-14",
  },

  Q0144: {
    original: {
      language: "Classical Chinese",
      text: "知之者不如好之者，好之者不如樂之者。",
      note:
        "The repeated object is 之, a pronoun referring back to the Way. The English has to choose a noun for it, and the choice goes a long way toward deciding what the sentence seems to be about.",
    },
    variants: [
      "They who know the truth are not equal to those who love it.",
      "Those who know the truth are not equal to those who love it.",
      "The one who knows is not equal to the one who loves.",
    ],
    attribution:
      "Analects 6.20. The familiar English “they who know the truth” comes from a nineteenth-century translation that expanded the pronoun 之 into “the truth,” and the phrase then travelled as a freestanding aphorism — complete with the “they who” construction that belongs to Victorian English, not to Confucius. The original ranks three relations to the Way: knowing it, loving it, delighting in it. The third stage is the one Confucius puts highest, and it is the one the popular English version drops entirely.",
    lastVerified: "2026-09-14",
  },

  Q0175: {
    original: {
      language: "Chinese",
      text: "敬業與樂業",
      note:
        "The title of Liang Qichao's 1922 talk to students. The archive's English passage is a condensation of the talk's argument rather than a translation of one sentence, and it is marked as such with an ellipsis.",
    },
    attribution:
      "This is a speech, delivered at a school, and it has no single citable sentence behind the English rendering. Treating the condensed English as if it were a quotable line misrepresents its form: the interest of the passage is that Liang is arguing against the sharp division between work done for duty and work done for enjoyment, which is a position developed across a whole address.",
    lastVerified: "2026-09-14",
  },

  Q0183: {
    original: {
      language: "Latin",
      text: "Cum enim gratia non tollat naturam, sed perficiat.",
      note:
        "The sentence is subordinate in the Latin — “since grace does not destroy nature but perfects it” — inside a reply to an objection. The English rendering promotes it to a standalone assertion.",
    },
    variants: [
      "Grace does not destroy nature, but perfects it.",
      "Grace perfects nature.",
    ],
    attribution:
      "Summa Theologiae I, q.1, a.8, reply to the second objection, where Aquinas is answering the charge that theology should not use philosophy. The sentence is his justification for borrowing from pagan philosophers: grace completes the natural powers it finds rather than replacing them. Quoted as a standalone maxim about grace it loses that it is, in place, an argument about what theologians may take from Aristotle.",
    lastVerified: "2026-09-14",
  },

  Q0186: {
    original: {
      language: "English",
      text:
        "Whence has it all the materials of reason and knowledge? To this I answer, in one word, from experience.",
      note:
        "Seventeenth-century English, capitalised as Locke wrote it. The question is his own, put in order to be answered.",
    },
    attribution:
      "An Essay Concerning Human Understanding, II.i.2. The doctrine is routinely labelled “tabula rasa,” and that Latin phrase is not Locke's — it comes from earlier scholastic and Aristotelian usage. Locke's own image in the same chapter is “white paper.” The substitution matters because “blank slate” suggests an entirely passive mind, whereas the chapter's point is about the origin of ideas, not about the absence of innate powers.",
    lastVerified: "2026-09-14",
  },

  Q0196: {
    original: {
      language: "German",
      text: "Alles wirkliche Leben ist Begegnung.",
      note:
        "One sentence closing the first part of Ich und Du (1923). English translations diverge sharply: “All real living is meeting” and “All actual life is encounter” are the same German.",
    },
    variants: [
      "All real living is meeting.",
      "All actual life is encounter.",
    ],
    attribution:
      "The variance here is not a corruption but a genuine split in the English tradition of translating Buber, so two readers citing different renderings of the same German line can both be right about the source and disagree about the words. Buber means a specific kind of relation — the I–Thou encounter, which is not a meeting in the scheduling sense — and the plain English word “meeting” has drifted far from that since the translation was made.",
    lastVerified: "2026-09-14",
  },

  Q0197: {
    original: {
      language: "French",
      text: "L'attention est la forme la plus rare et la plus pure de la générosité.",
      note:
        "From a letter to the poet Joë Bousquet dated 13 April 1942. The archive keeps the date because the sentence has no printed source: it exists in Weil's correspondence.",
    },
    variants: [
      "Attention is the rarest and purest form of generosity.",
      "Attention is the purest and rarest form of generosity.",
      "Attention is the rarest form of generosity.",
    ],
    attribution:
      "Frequently misfiled as coming from Gravity and Grace or from Waiting for God, which were assembled and published after Weil's death. It comes from a letter, and the correspondent matters: Weil is writing to a wounded poet about what one person owes another's suffering, so “attention” here is a demanding discipline of self-emptying, not the everyday sense of the word. It is also sometimes attributed to Simone de Beauvoir on the strength of the shared first name.",
    lastVerified: "2026-09-14",
  },

  Q0330: {
    original: {
      language: "Latin",
      text:
        "Ego sum, ego existo, quoties a me profertur, vel mente concipitur, necessario esse verum.",
      note:
        "“I am, I exist — as often as it is uttered by me, or conceived in mind, it is necessarily true.” The English rendering trims the repeated “as often as” clause that makes the claim a claim about each occurrence.",
    },
    attribution:
      "Meditations II. This is the sentence Descartes actually wrote, and the reason the famous “cogito” formula is a summary rather than a quotation: the Meditations version states the necessary truth of the proposition each time it is thought, which is a stronger and more carefully guarded claim than “I think, therefore I am.”",
    lastVerified: "2026-09-14",
  },

  Q0432: {
    original: {
      language: "Latin",
      text: "Scientia et potentia humana in idem coincidunt.",
      note:
        "Literally “knowledge and human power coincide in the same thing.” The English renders coincidunt as “meet in one,” which keeps the sense of two things arriving at one point.",
    },
    variants: [
      "Knowledge is power.",
      "Human knowledge and human power meet in one.",
    ],
    attribution:
      "Novum Organum I, Aphorism 3. Bacon's aphorism continues: because the cause is unknown, the effect is lost. So he is not coining a slogan about education but stating a condition on action — you cannot produce an effect whose cause you have not found. The English tag “knowledge is power” is a much later and looser reduction of the sentence, and it is not Bacon's wording in any of his works.",
    lastVerified: "2026-09-14",
  },

  Q0436: {
    original: {
      language: "Ancient Greek",
      text: "ἡ ἀρετὴ μεσότης τις ἄρα ἐστίν.",
      note:
        "“Virtue, then, is a kind of mean.” The indefinite τις matters — “a kind of” — and the English tag “virtue lies in a mean” drops it.",
    },
    variants: [
      "Virtue lies in a mean.",
      "Virtue is the mean between two extremes.",
      "Moderation in all things.",
    ],
    attribution:
      "Nicomachean Ethics II.6, where the definition is immediately qualified: the mean is relative to the agent, not arithmetic, and a few lines later Aristotle adds that not every action admits one — there is no right amount of adultery or murder. “Moderation in all things” is not Aristotle and is close to the opposite of what the qualification says.",
    lastVerified: "2026-09-14",
  },

  Q0443: {
    original: {
      language: "French",
      text:
        "De tâcher toujours plutôt à me vaincre que la fortune, et à changer mes désirs que l'ordre du monde.",
      note:
        "The archive's English is a fragment of this clause: it keeps the second half and drops “to try always rather to overcome myself than fortune.”",
    },
    attribution:
      "Discourse on the Method, Part III. Quoted without its first half the line sounds like advice to accept circumstances; with it, the emphasis falls on self-mastery first and Stoic acceptance as the residue. This is one of the places where a half-quotation reverses the balance of a sentence.",
    lastVerified: "2026-09-14",
  },

  Q0395: {
    variants: [
      "I disapprove of what you say, but I will defend to the death your right to say it.",
      "I do not agree with what you have to say, but I'll defend to the death your right to say it.",
    ],
    attribution:
      "Not Voltaire. The sentence was written by Evelyn Beatrice Hall in her 1906 biography of Voltaire, under the pen name S. G. Tallentyre, as her own summary of his attitude. Voltaire's actual surviving writing on the subject is a 1770 letter to a correspondent containing a much blunter and narrower statement about the risks of persecution. Hall's sentence has been printed under Voltaire's name ever since, and the archive keeps it in the corpus flagged as a traditional attribution rather than presenting it as his wording.",
    lastVerified: "2026-09-14",
  },

  Q0314: {
    original: {
      language: "French",
      text: "Le doute n'est pas un état bien agréable, mais l'assurance est un état ridicule.",
      note:
        "“Doubt is not a very agreeable state, but assurance is a ridiculous one.” From a letter, not a published work.",
    },
    attribution:
      "The line comes from Voltaire's correspondence — a letter of November 1770 — rather than from the Philosophical Dictionary or any of the works usually cited for it. Like most of Voltaire's sharpest sentences it was written to one reader, which is why the phrasing is looser than his published prose.",
    lastVerified: "2026-09-14",
  },
};

/**
 * Quotes whose source-forward metadata has been reviewed against the cited
 * edition. Batch 1 is the top-impression and top-ranking set: the five
 * long-tails that have already reached positions 1–3, plus the pages carrying
 * the largest impression counts in Search Console.
 *
 * The batches are recorded so the rollout stays visible and incremental. A
 * site-wide metadata rewrite is a batch-rewrite signal, and a batch-rewrite
 * signal is what invited the August re-evaluation; fifty reviewed pages a week
 * is deliberate, not an unfinished job.
 */
export const VERIFICATION_BATCHES: Record<string, string[]> = {
  "batch-1-2026-09-14": [
    "Q0001",
    "Q0002",
    "Q0003",
    "Q0004",
    "Q0032",
    "Q0054",
    "Q0055",
    "Q0059",
    "Q0062",
    "Q0070",
    "Q0071",
    "Q0072",
    "Q0074",
    "Q0102",
    "Q0120",
    "Q0134",
    "Q0135",
    "Q0136",
    "Q0140",
    "Q0144",
    "Q0175",
    "Q0183",
    "Q0186",
    "Q0196",
    "Q0197",
    "Q0330",
    "Q0395",
    "Q0432",
    "Q0436",
    "Q0443",
    "Q0314",
  ],
};

const batchIds = new Set(Object.values(VERIFICATION_BATCHES).flat());

export function isInVerificationBatch(id: string) {
  return batchIds.has(id.toUpperCase());
}

export function verificationNote(id: string) {
  return quoteVerification[id.toUpperCase()];
}

/**
 * The two dates the corpus itself last moved, used as the fallback “last
 * verified” for passages with no per-quote register entry.
 *
 * They are different on purpose. Q0001–Q0499 with no written commentary have
 * not changed since the corpus stabilised on 2026-08-26. The later quotations,
 * and the legacy passages that received passage-specific commentary, were
 * written on 2026-08-30. Stamping one date on all of them would tell a crawler
 * that nine hundred pages changed on the same day, which is the exact signal
 * the sitemap work exists to stop sending.
 */
export const LEGACY_CORPUS_DATE = "2026-08-26";
export const CORPUS_UNLOCK_DATE = "2026-08-30";

export function corpusReviewDate(id: string, hasOwnCommentary: boolean) {
  const numeric = Number(id.replace(/^Q/i, ""));
  if (Number.isFinite(numeric) && numeric > 499) return CORPUS_UNLOCK_DATE;
  return hasOwnCommentary ? CORPUS_UNLOCK_DATE : LEGACY_CORPUS_DATE;
}

/**
 * ISO 639 codes for the languages recorded above, so the structured data can
 * state the language of the original rather than only naming it in prose.
 * Deliberately partial: an entry missing here means the language is either a
 * pair (“Latin and French”) or too uncertain to assert, and the schema simply
 * omits the field rather than guessing a code.
 */
export const LANGUAGE_CODES: Record<string, string> = {
  "Ancient Greek": "grc",
  Latin: "la",
  French: "fr",
  German: "de",
  "Classical Chinese": "lzh",
  Chinese: "zh",
  Pali: "pi",
  English: "en",
  "Koine Greek": "grc",
  Danish: "da",
};

export function languageCode(language: string) {
  return LANGUAGE_CODES[language];
}
